<template>
	<view>
		<view class="title">
			<text>
				Privacy Agreement
			</text>
		</view>
		<view class="text">
			<text>
				    You (user) are specially reminded to read this privacy agreement (hereinafter referred to as "the agreement") carefully before registering as a user to ensure that you fully understand the terms of this agreement. Please carefully read and choose to accept or not accept this agreement. Your registration, login, use and other behaviors will be deemed as your acceptance of this agreement, and you agree to be bound by the terms of this agreement. This agreement stipulates the rights and obligations between our company and users regarding software or services. "User" refers to the individual who registers, logs in and uses this service. This agreement can be updated by our company at any time. Once the updated agreement terms are published, they will replace the original agreement terms without further notice. Users can check the latest version of the agreement terms in our products. After modifying the terms of the agreement, if the user does not accept the modified terms, please immediately stop using the services provided by the company, and the user's continued use of the services will be deemed to have accepted the modified agreement.
				
				First, confidentiality of data recovery information
				
				When you use the data recovery products or services provided by the company, the user must allow the company to use any information in the hardware equipment, including but limited to the hard disk, for data recovery. Our company guarantees the confidentiality of the information. After data recovery, no matter whether the user copies the data or not, our company will not leave a backup of any data in the equipment.
				
				
				Second, collection of personal information
			
				Please know that the company collects your personal information below for the purpose of providing services and improving products and services. The company attaches great importance to the protection of your privacy. The company will strictly abide by the principle of "legality, legitimacy and necessity" when collecting your information. And you know that if you do not provide the relevant information required by the company to provide you with services, your use experience and effect may be affected. Considering the relevance of the services provided by the company, you have agreed that the company will collect the information you enter when using the products and services or provide to us in other ways:
				
				1 mobile device model, device name, unique identifier, browser type, system language, operating system version, application version, WiFi network environment, log information.
				2 when you register or activate your login account, your personal registration information will be collected, including mobile phone number, user name, password, user avatar and nickname.
				3. During the service, we will record your geographical location information.
				The company reserves the right to make any changes to the collection of the above information without notice, provided that the laws and regulations permit.
				
				Third, data information management
				
				1. The user's personal information collected and generated by the company in the people's Republic of China is stored on the server in the people's Republic of China. If it is really necessary to transmit your personal information abroad, you will obtain your authorization in advance, carry out cross-border data transmission in accordance with the requirements of relevant laws, regulations and policies, and perform the obligation of confidentiality for your personal information.
				2. During the period when your information is stored on our server, our company will spare no effort to maintain the security of your information and effectively ensure the reasonable use of your information.
				3.without your prior consent, we will not disclose or transfer your information to a third party unless:
				
				(1) Obtain your explicit consent or authorization in advance;
				(2) Related to national security and national defense security;
				(3) Related to public safety, public health and major public interests;
				(4) Related to criminal investigation, prosecution, trial and judgment execution;
				(5) The collected personal information is disclosed to the public by yourself;
				(6) Collect your personal information from legally disclosed information, such as legal news reports, government information disclosure and other channels;
				(7) Share with related parties, partners and third-party service providers of the company, but only based on the sharing of basic information;
				(8) Other circumstances stipulated by laws and regulations.
				
				Fourth, the protection of personal privacy
				
				1. If the company finds or receives reports or complaints from others about the user's violation of this privacy agreement or the use agreement, the company has the right to review and delete the relevant contents, including but not limited to user data and posting records, and impose penalties on the violating account, including but not limited to warnings, account blocking, device blocking and function blocking, depending on the seriousness of the case, and notify the user of the handling results.
				2. Users who are banned for violating the user agreement can contact the company by themselves. Among them, users who have been banned will automatically resume the banned function after the expiration of the ban period. Banned users can submit appeals, and the company will review the appeals and decide whether to change the punishment measures at its own reasonable discretion.
				3. The user understands and agrees that the company has the right to punish the acts in violation of relevant laws and regulations or the provisions of this agreement according to its reasonable judgment, take appropriate legal actions against any user who violates laws and regulations, and keep relevant information and report to the relevant departments according to laws and regulations. The user shall bear all legal responsibilities arising therefrom.
				4. The user understands and agrees that for any claim, demand or loss claimed by any third party, including reasonable attorney's fees, caused or incurred by the user's violation of the agreement, the user shall compensate the company, cooperative companies and affiliated companies and protect them from damage.
				
				Fifth, instructions for users to release information
				
				The use of products or services provided by the company may involve the release of users' own information. It is hereby agreed that:
				Users are not allowed to make, upload, copy, publish and disseminate the following contents prohibited by laws, regulations and policies:
				
				(1) Opposing the basic principles defined in the constitution;
				(2) Endangering national security, divulging state secrets, subverting state power, and undermining national unity;
				(3) Damaging the honor and interests of the state;
				(4) Inciting national hatred and discrimination and undermining national unity;
				(5) Undermining the state's religious policies and propagating cults and feudal Superstitions;
				(6) Spreading rumors, disturbing social order and destroying social stability;
				(7) Spreading obscenity, pornography, gambling, violence, murder, terror or abetting crime;
				(8) Insulting or slandering others and infringing upon the legitimate rights and interests of others;
				(9) Information containing other contents prohibited by laws and administrative regulations.
				
				Users are also not allowed to make, upload, copy, publish and disseminate the following contents that interfere with the normal operation of the "service" and infringe the legitimate rights and interests of other users or third parties:
				
				(1) Containing explicit or sexual implication;
				(2) Containing abusive, threatening or threatening contents;
				(3) Containing harassment, garbage advertisements, malicious information, and deception information;
				(4) Involving others' privacy, personal information or data;
				(5) Infringing upon others' reputation rights, portrait rights, intellectual property rights, trade secrets and other legitimate rights;
				(6) It contains other information that interferes with the normal operation of this service and infringes the legitimate rights and interests of other users or third parties.
				
				Vi. other instructions
				
				1. The company solemnly reminds users to pay attention to the clauses in this agreement that exempt users from liability and restrict users' rights. Users are requested to read them carefully and consider the risks independently. Minors should read this agreement accompanied by their legal guardian.
				2. The validity, interpretation and dispute settlement of this Agreement shall be governed by the mainland laws of the people's Republic of China. In case of any dispute or controversy between the user and the company, it shall be settled through friendly negotiation first. If the negotiation fails, the user agrees to submit the dispute or controversy to the people's court with jurisdiction in the place where the company is domiciled.
				3. Any provision of this agreement is invalid or unenforceable for any reason, and the remaining provisions are still valid and binding on both parties.
				4. The user must confirm the ownership of the equipment and data that need to recover the data; Or ensure that it is authorized by the owner of the equipment or data; Otherwise, we have the right to terminate the data recovery service at any time and reserve the right to investigate the legal responsibility of the user;
				
				The copyright of this privacy agreement is owned by the company, and all rights to interpret this privacy agreement are reserved.
				If there is any dispute between you and our company about the content of this privacy agreement or its implementation, both parties should conduct friendly negotiation; If the negotiation fails, either party can bring a lawsuit to the people's court with jurisdiction in the place where our company is domiciled.
				The terms of this privacy agreement are severable. If one term is deemed invalid by applicable law, the other terms will not be affected and shall continue to be valid and enforced.
				
				
				By now, you must have read and understood this privacy agreement in detail, and agree to strictly abide by the terms and conditions.
			</text>
		</view>

		<!-- <view class="lastPara">
			<text>
				By now, you must have read and understood this privacy agreement in detail, and agree to strictly abide by the terms and conditions.
			</text>
		</view> -->
		
	</view>
</template>

<script>
	
</script>

<style>
	.title {
		font-size: 25px;
		font-weight: 500;
		margin-top: 20px;
		margin-left: 75px;

	}

	.text {
		font-size: 15px;
		margin-top: 30px;
		color: darkgray;
		text-align: justify;
		
	}

	/* .lastPara {
		font-size: 18px;
		margin-top: 100rpx;
		font-weight: 600;
		display: block;
		margin: 0 auto;
		

	} */
</style>
